import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useRef, useState } from "react";
import RestAllWritingOutputWindow from "@/components/outputScreen/restAllWriting";
import { ShinyButton } from "@/components/ui/shiny-button";
import { AuroraText } from "@/components/ui/aurora-text";
import FAQSection from "@/components/component/FAQSection";
import toast from "react-hot-toast";

const aiDetectorFAQs = [
  {
    question: "What is an AI Detector tool?",
    answer:
      "An AI Detector tool analyzes text content to determine whether it was written by a human or generated by AI, providing a score that reflects the likelihood of AI authorship.",
  },
  {
    question: "How does the AI Detector work?",
    answer:
      "It uses advanced machine learning and natural language processing algorithms to evaluate writing patterns, style, and features typical of AI-generated versus human-written text.",
  },
  {
    question: "What does the detection score mean?",
    answer:
      "The score ranges from 0 to 100, where 0 (green) means the content is fully human-written, and 100 (red) indicates it is likely AI-generated or machine-written.",
  },
  {
    question: "Why is AI detection important for SEO?",
    answer:
      "Search engines prioritize original, human-written content. Detecting AI-generated text helps maintain content authenticity, boosts SEO rankings, and ensures compliance with search guidelines.",
  },
  {
    question: "What type of text should I input for accurate detection?",
    answer:
      "For best results, input substantial and meaningful text such as paragraphs, articles, or blog posts rather than short or fragmented sentences.",
  },
  {
    question: "Can the AI Detector identify all AI-generated content?",
    answer:
      "While highly accurate, no AI detector is 100% perfect due to the evolving nature of AI writing. It is recommended to combine detection results with manual content review.",
  },
  {
    question: "Is the AI Detector tool free to use?",
    answer:
      "Many AI Detector tools offer free usage with limitations, making it accessible for individuals and businesses to verify content authenticity easily.",
  },
  {
    question: "How fast is the AI Detector tool?",
    answer:
      "Detection results are generated instantly, allowing you to quickly verify content authenticity before publishing or sharing.",
  },
  {
    question: "Can AI detection improve my website’s credibility?",
    answer:
      "Yes, using AI detection tools helps ensure your website publishes authentic, trustworthy content, enhancing your brand’s credibility and user trust.",
  },
  {
    question: "How can I use AI Detector results effectively?",
    answer:
      "Use the results to review and improve your content quality, avoid penalties from search engines, and maintain high editorial standards across your digital platforms.",
  },
];

const DetectorPage = () => {
  const guideRef = useRef(null);
  const [isDark, setIsDark] = useState(true);
  const [text, setText] = useState("");

  const [detectedTextLoading, setDetectedTextLoading] = useState(false);
  const [detectedTextResponse, setDetectedTextResponse] = useState("");
  const handleDetectedTextGenerate = async () => {
    if(!text || text.trim() === "") {
      toast.error("Please fill in the text field!");
      return;
    }
    try {
      setDetectedTextLoading(true);
      const res = await fetch("https://www.magiwriter.com/api/generate/detect", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
        body: JSON.stringify({text}),
      });
      const response = await res.json();
      setDetectedTextResponse(response.detectedText);
    } catch (error) {
      console.error("Error converting robotic text into human tone!:", error);
    } finally {
      setDetectedTextLoading(false);
    }
  };

  const handleResetFields = () => {
    setText("");
  };

  return (
    <div className="max-w-screen flex flex-col items-center gap-[3vw] mt-[1vw] text-white">
      <header className="w-full flex flex-col items-center gap-[1vw] mt-[14vw] md:mt-[14vw] lg:mt-[8vw]">
        <h1 className="font-bold text-4xl md:text-5xl lg:text-4xl font-nunito">
          <AuroraText
            colors={[
              "#60efff",
              "#0061ff",
              "#40c9ff",
              "#cbff49",
              "#ff8989",
              "#fff95b",
            ]}
            speed={1.5}
          >
            AI Detector
          </AuroraText>
        </h1>
        <h2 className="max-w-[60%] text-center font-semibold text-2xl md:text-4xl lg:text-2xl font-nunito text-gray-300">
          Create fully optimized, human-quality blog blogs in seconds using
          structured inputs for keywords, tone, audience, SEO, images, tables,
          FAQs, and more—no prompt writing required.
        </h2>
      </header>
      <section className="w-full flex flex-col items-center gap-[1vw]">
        <p className="max-w-[40%] text-center text-xl md:text-3xl lg:text-2xl font-nunito text-gray-100">
          Want to know how you could leverage Magiwriter's AI Blog Writer to
          generate top class industry grade blogs with best SEO techniques? Look
          no further, just check down bellow.
        </p>
        <ShinyButton onClick={()=> guideRef.current.scrollIntoView({behavior: "smooth"})} className={"bg-white/15 md:text-4xl lg:text-sm m-0"}>
          Check Full Guide
        </ShinyButton>
      </section>
      <main
        className={`w-[95%] xl:w-[60%] flex flex-col items-center gap-[6vw] lg:gap-[5vw] xl:gap-[2vw] border ${
          isDark
            ? "bg-black/35 border-gray-300/25"
            : "bg-white/55 border-gray-400/15"
        } blur-in-3xl z-10 p-[4vw] xl:p-[2vw] xl:my-[1vw] rounded-3xl font-nunito`}
      >
        <section className="w-full flex flex-col items-center gap-[5vw] xl:gap-[1vw]">
          <div className="w-full flex flex-col items-start gap-[2vw] xl:gap-[0.5vw]">
            <Label
              className={"text-xl md:text-3xl lg:text-base"} htmlFor="message">
              Paste your text content and get a score based on if this content
              is human written or ai/robot written.
            </Label>
            <Textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              className={`border h-[14vw] xl:h-[5vw] ${
                isDark
                  ? "bg-gray-900 text-white placeholder:text-gray-300 border-gray-600"
                  : "bg-white text-black placeholder:text-gray-400"
              } shadow-lg resize-none overflow-auto text-xl md:text-3xl lg:text-base p-[2vw] lg:p-[1vw] xl:p-[0.5vw]`}
              placeholder="Write/paste here..."
            />
          </div>
        </section>
        <section className="w-full flex flex-col items-center gap-[5vw] xl:gap-[1vw]">
          <Button
            onClick={handleDetectedTextGenerate}
            className={`w-full font-nunito cursor-pointer bg-linear-from-l bg-linear-to-r from-blue-500/50 via-pink-500/70 to-orange-500/65 ${
              isDark
                ? "text-white hover:bg-white/20"
                : "text-black hover:bg-black/20"
            } shadow-xl text-xl md:text-3xl lg:text-base px-[2vw] lg:px-[1vw] xl:px-[0.5vw] py-[4vw] lg:py-[2vw] xl:py-[1vw] transition-all duration-200`}
          >
            Detect Text
          </Button>
          <Button
            onClick={handleResetFields}
            variant={"outline"}
            className={`w-full font-nunito cursor-pointer ${
              isDark
                ? "hover:bg-red-700/20 hover:text-white bg-gray-800/55 border-gray-600/80 text-white"
                : "hover:bg-red-700/20 hover:text-black bg-white text-black"
            } transition-all duration-200 text-xl md:text-3xl lg:text-base px-[2vw] lg:px-[1vw] xl:px-[0.5vw] py-[4vw] lg:py-[2vw] xl:py-[1vw]`}
          >
            Reset All Fields
          </Button>
        </section>
        {(detectedTextLoading || detectedTextResponse) && (
          <RestAllWritingOutputWindow
            restAllWritingMarkdown={detectedTextResponse}
            isLoading={detectedTextLoading}
            isDark={isDark}
          />
        )}
      </main>
      <section ref={guideRef} className="max-w-full flex flex-col items-center gap-[4vw] mt-[10vw]">
        <div className="w-full flex flex-col items-center gap-[1vw]">
          <h2 className="lg:max-w-[45%] max-w-[70%] font-bold text-3xl md:text-5xl lg:text-3xl text-center">
            🤖 Complete Guide to Using the AI Detector Tool for Authenticity &
            Content Integrity
          </h2>
          <p className="lg:max-w-[60%] max-w-[80%] text-2xl md:text-3xl lg:text-xl text-center">
            Our AI Detector is designed for{" "}
            <span className="font-bold">
              identifying AI-generated versus human-written text with precision
            </span>{" "}
            — simply paste your content to analyze its origin and receive a{" "}
            <span className="font-bold">
              confidence score indicating human or AI authorship
            </span>{" "}
            within seconds.
          </p>
          <p className="lg:max-w-[60%] max-w-[80%] text-2xl md:text-3xl lg:text-xl text-center text-gray-300 mt-[1vw]">
            This guide explains{" "}
            <span className="font-bold">the text input field</span>, how to use
            it effectively, and how it helps maintain content authenticity,
            trust, and SEO quality.
          </p>
        </div>

        <div className="lg:max-w-[60%] max-w-[90%] space-y-16">
          <div className="max-w-full space-y-2 bg-gray-800/80 border border-gray-400/40 p-[4vw] lg:p-[1vw] rounded-xl">
            <h3 className="text-2xl md:text-3xl lg:text-2xl font-semibold text-white">
              🔍 1. Text Input
            </h3>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Purpose:</span> Submit
              the content you want to evaluate for AI or human authorship.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Best Practice:</span>{" "}
              Paste meaningful and sufficient text (e.g., paragraphs, articles)
              for accurate detection results.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Impact:</span> Enables
              reliable AI content detection to uphold content integrity and
              quality.
            </p>
          </div>
        </div>

        <div className="max-w-full lg:max-w-[45%] w-[80%] flex flex-col items-center pt-8 border-t border-gray-700 space-y-4">
          <h3 className="text-2xl md:text-3xl lg:text-2xl font-bold text-white">
            📊 Why This AI Detector Boosts Content Authenticity & SEO Trust
          </h3>
          <p className="text-2xl lg:text-base">
            This AI Detector follows{" "}
            <span className="font-semibold text-white">
              cutting-edge machine learning and NLP techniques
            </span>{" "}
            to deliver precise detection:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">
                Authenticity Verification
              </span>{" "}
              – Distinguishes between human and AI-generated text
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">SEO Integrity</span> –
              Helps maintain high-quality, original content for search rankings
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Trust Building</span> –
              Ensures your audience trusts your content’s source and value
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Instant Analysis</span>{" "}
              – Provides quick and clear scoring from 0 (human) to 100 (AI)
            </li>
          </ul>

          <p className="text-2xl lg:text-base">
            It aligns with{" "}
            <span className="font-semibold text-white">
              SEO best practices, content authenticity standards, and digital
              trust frameworks
            </span>
            , including:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">
              Detection of AI-generated content in blogs, articles, and
              marketing
            </li>
            <li className="text-2xl lg:text-base">
              Ensuring compliance with search engine guidelines on originality
            </li>
            <li className="text-2xl lg:text-base">
              Supporting content creators and publishers with integrity tools
            </li>
            <li className="text-2xl lg:text-base">Improving user trust and brand credibility online</li>
          </ul>
        </div>

        <div className="max-w-full lg:max-w-[45%] w-[80%] flex flex-col items-center pt-8 border-t border-gray-700 space-y-4">
          <h3 className="text-2xl md:text-3xl lg:text-2xl font-bold text-white">
            🧠 Final Tips for Accurate AI Detection and Content Quality
          </h3>
          <p className="text-2xl lg:text-base">For the best detection results and to maintain content quality:</p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">
              Use{" "}
              <span className="font-semibold text-white">
                substantial text samples (several sentences or paragraphs)
              </span>{" "}
              for accurate analysis
            </li>
            <li className="text-2xl lg:text-base">
              Avoid extremely short or ambiguous text that may reduce detection
              precision
            </li>
            <li className="text-2xl lg:text-base">
              Use the tool to verify content authenticity before publishing or
              sharing
            </li>
            <li className="text-2xl lg:text-base">
              Combine AI detection with manual review for best content integrity
            </li>
            <li className="text-2xl lg:text-base">
              Stay updated with evolving AI content detection technology and SEO
              guidelines
            </li>
          </ul>
        </div>
      </section>
      <section className="max-w-full lg:w-[60%] w-[90%] flex flex-col items-center mt-[10vw]">
        <FAQSection
          faqs={aiDetectorFAQs}
          title="Frequently Asked Questions"
          subtitle="Everything you need to know about Magiwriter's AI Detector and how it can transform your content writing game."
        />
      </section>
    </div>
  );
};

export default DetectorPage;
