import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useRef, useState } from "react";
import ImageView from "@/components/outputScreen/Image";
import { AuroraText } from "@/components/ui/aurora-text";
import { ShinyButton } from "@/components/ui/shiny-button";
import FAQSection from "@/components/component/FAQSection";
import toast from "react-hot-toast";

const imageGeneratorFAQs = [
  {
    question: "What is an AI Image Generator?",
    answer:
      "An AI Image Generator is a tool that creates high-quality, realistic, and creative images from text descriptions, helping users generate visuals for websites, marketing, social media, and digital content creation.",
  },
  {
    question: "How does the AI Image Generator work?",
    answer:
      "The tool analyzes your idea prompt along with image settings like resolution, aspect ratio, and format to generate visually accurate, high-resolution AI images optimized for your specific use case.",
  },
  {
    question: "What should I write in the idea field?",
    answer:
      "Enter a clear and detailed description of the image you want, including subject, style, mood, and context, such as “modern office workspace,” “fantasy landscape,” or “realistic product photography.”",
  },
  {
    question: "Why is resolution important in AI image generation?",
    answer:
      "Resolution determines the clarity and quality of the generated image. Higher resolutions produce sharper visuals suitable for websites, marketing materials, presentations, and professional design use.",
  },
  {
    question: "How does aspect ratio affect the generated image?",
    answer:
      "Aspect ratio controls the shape of the image, making it suitable for different platforms such as square images for social media, widescreen for banners, or vertical for mobile and story formats.",
  },
  {
    question: "What image formats can I choose from?",
    answer:
      "You can generate images in formats such as JPG and PNG, allowing compatibility with websites, social platforms, design software, and digital marketing tools.",
  },
  {
    question: "Can this tool be used for SEO and marketing content?",
    answer:
      "Yes, the AI Image Generator helps create optimized visuals that improve user engagement, dwell time, and visual search performance, contributing to better SEO rankings and online visibility.",
  },
  {
    question: "Is the AI Image Generator suitable for commercial use?",
    answer:
      "Yes, the tool can be used to generate images for marketing, advertising, branding, websites, social media, and business presentations, depending on your usage rights and platform policies.",
  },
  {
    question: "Can I customize the generated images?",
    answer:
      "Yes, you can regenerate images using different prompts, resolutions, aspect ratios, and formats to achieve the exact style and output you need.",
  },
  {
    question: "Who should use the AI Image Generator?",
    answer:
      "This tool is ideal for marketers, designers, content creators, bloggers, business owners, social media managers, and anyone who needs fast, high-quality visual content.",
  },
  {
    question: "Does this tool improve website performance and engagement?",
    answer:
      "Yes, high-quality visuals generated by this tool increase user engagement, reduce bounce rates, and improve overall website performance, which positively impacts SEO rankings.",
  },
  {
    question: "Is the AI Image Generator free to use?",
    answer:
      "Many versions of the AI Image Generator are available for free, allowing users to create professional-quality images without subscriptions or advanced design skills.",
  },
];

const ImageGeneratorPage = () => {
  const guideRef = useRef(null);
  const [isDark, setIsDark] = useState(true);
  const [idea, setIdea] = useState("");
  const [resolution, setResolution] = useState("auto");

  const [imageLoading, setImageLoading] = useState(false);
  const [imageResponse, setImageResponse] = useState("");

  const handleImageGenraiton = async () => {
    if(!idea || idea.trim() === "") {
      toast.error("Please fill in the idea field!");
      return;
    }
    try {
      setImageLoading(true);
      const res = await fetch("/api/generate/image", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
        body: JSON.stringify({ idea, resolution }),
      });
      const json = await res.json();
      console.log("Response: ", json);
      setImageResponse(json.image);
    } catch (error) {
      console.error("Error generating image:", error);
    } finally {
      setImageLoading(false);
    }
  };

  const handleResetFields = () => {
    setIdea("");
    setResolution("");
    setAspect_ration("");
    setImage_type("");
  };

  return (
    <div className="max-w-screen flex flex-col items-center gap-[3vw] mt-[1vw] text-white">
      <header className="w-full flex flex-col items-center gap-[1vw] mt-[14vw] md:mt-[14vw] lg:mt-[8vw]">
        <h1 className="font-bold text-4xl md:text-5xl lg:text-4xl font-nunito">
          <AuroraText
            colors={[
              "#60efff",
              "#0061ff",
              "#40c9ff",
              "#cbff49",
              "#ff8989",
              "#fff95b",
            ]}
            speed={1.5}
          >
            AI Image Generator
          </AuroraText>
        </h1>
        <h2 className="max-w-[60%] text-center font-semibold text-2xl md:text-4xl lg:text-2xl font-nunito text-gray-300">
          Create fully optimized, human-quality blog blogs in seconds using
          structured inputs for keywords, tone, audience, SEO, images, tables,
          FAQs, and more—no prompt writing required.
        </h2>
      </header>
      <section className="w-full flex flex-col items-center gap-[1vw]">
        <p className="max-w-[40%] text-center text-xl md:text-3xl lg:text-2xl font-nunito text-gray-100">
          Want to know how you could leverage Magiwriter's AI Blog Writer to
          generate top class industry grade blogs with best SEO techniques? Look
          no further, just check down bellow.
        </p>
        <ShinyButton onClick={()=> guideRef.current.scrollIntoView({behavior: "smooth"})} className={"bg-white/15 md:text-4xl lg:text-sm m-0"}>
          Check Full Guide
        </ShinyButton>
      </section>
      <main
        className={`w-[95%] xl:w-[60%] flex flex-col items-center gap-[6vw] lg:gap-[5vw] xl:gap-[2vw] border ${
          isDark
            ? "bg-black/35 border-gray-300/25"
            : "bg-white/55 border-gray-400/15"
        } blur-in-3xl z-10 p-[4vw] xl:p-[2vw] xl:my-[1vw] rounded-3xl font-nunito`}
      >
        <section className="w-full flex flex-col items-center gap-[5vw] xl:gap-[1vw]">
          <div className="w-full flex flex-col items-start gap-[2vw] xl:gap-[0.5vw]">
            <Label
              className={"text-xl md:text-3xl lg:text-base"}
              htmlFor="message"
            >
              Describe your idea about the image you want to generate
            </Label>
            <Textarea
              value={idea}
              onChange={(e) => setIdea(e.target.value)}
              className={`border h-[14vw] xl:h-[5vw] ${
                isDark
                  ? "bg-gray-900 text-white placeholder:text-gray-300 border-gray-600"
                  : "bg-white text-black placeholder:text-gray-400"
              } shadow-lg resize-none overflow-auto text-xl md:text-3xl lg:text-base p-[2vw] lg:p-[1vw] xl:p-[0.5vw]`}
              placeholder="Describe your idea here..."
            />
          </div>
          <div className="w-full flex flex-wrap justify-between items-center gap-[2vw]">
            <div className="w-[45%] xl:w-[20%] flex flex-col items-start gap-[2vw] xl:gap-[0.5vw]">
              <Label htmlFor="type">Resolution:</Label>
              <DropdownMenu>
                <DropdownMenuTrigger
                  className={`w-full border shadow-lg ${
                    isDark
                      ? "bg-gray-800 border-gray-600/80"
                      : "bg-white border-gray-400/15"
                  } rounded-md xl:rounded-lg px-[1vw] py-[1vw] xl:py-[0.5vw] text-xl md:text-3xl lg:text-base cursor-pointer`}
                >
                  {resolution}
                </DropdownMenuTrigger>
                <DropdownMenuContent
                  className={`border shadow-lg ${
                    isDark
                      ? "bg-gray-800 border-gray-600/80 text-white"
                      : "bg-white border-gray-400/15 text-black"
                  } text-xl md:text-3xl lg:text-base py-[2vw] lg:py-[1vw] xl:py-[0.5vw]`}
                >
                  <DropdownMenuItem
                    className={`cursor-pointer ${
                      isDark
                        ? "focus:bg-black focus:text-white text-white"
                        : "focus:bg-gray-200 focus:text-black text-black"
                    } text-xl md:text-3xl lg:text-base py-[2vw] lg:py-[1vw] xl:py-[0.5vw]`}
                    onClick={(e) => setResolution(e.target.innerText)}
                  >
                    auto
                  </DropdownMenuItem>
                  <DropdownMenuItem
                    className={`cursor-pointer ${
                      isDark
                        ? "focus:bg-black focus:text-white text-white"
                        : "focus:bg-gray-200 focus:text-black text-black"
                    } text-xl md:text-3xl lg:text-base py-[2vw] lg:py-[1vw] xl:py-[0.5vw]`}
                    onClick={(e) => setResolution(e.target.innerText)}
                  >
                    1024x1536
                  </DropdownMenuItem>
                  <DropdownMenuItem
                    className={`cursor-pointer ${
                      isDark
                        ? "focus:bg-black focus:text-white text-white"
                        : "focus:bg-gray-200 focus:text-black text-black"
                    } text-xl md:text-3xl lg:text-base py-[2vw] lg:py-[1vw] xl:py-[0.5vw]`}
                    onClick={(e) => setResolution(e.target.innerText)}
                  >
                    1536x1024
                  </DropdownMenuItem>
                  <DropdownMenuItem
                    className={`cursor-pointer ${
                      isDark
                        ? "focus:bg-black focus:text-white text-white"
                        : "focus:bg-gray-200 focus:text-black text-black"
                    } text-xl md:text-3xl lg:text-base py-[2vw] lg:py-[1vw] xl:py-[0.5vw]`}
                    onClick={(e) => setResolution(e.target.innerText)}
                  >
                    1024x1024
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </section>
        <section className="w-full flex flex-col items-center gap-[5vw] xl:gap-[1vw]">
          <Button
            onClick={handleImageGenraiton}
            className={`w-full font-nunito cursor-pointer bg-linear-from-l bg-linear-to-r from-blue-500/50 via-pink-500/70 to-orange-500/65 ${
              isDark
                ? "text-white hover:bg-white/20"
                : "text-black hover:bg-black/20"
            } shadow-xl text-xl md:text-3xl lg:text-base px-[2vw] lg:px-[1vw] xl:px-[0.5vw] py-[4vw] lg:py-[2vw] xl:py-[1vw] transition-all duration-200`}
          >
            Generate Image
          </Button>
          <Button
            onClick={handleResetFields}
            variant={"outline"}
            className={`w-full font-nunito cursor-pointer ${
              isDark
                ? "hover:bg-red-700/20 hover:text-white bg-gray-800/55 border-gray-600/80 text-white"
                : "hover:bg-red-700/20 hover:text-black bg-white text-black"
            } transition-all duration-200 text-xl md:text-3xl lg:text-base px-[2vw] lg:px-[1vw] xl:px-[0.5vw] py-[4vw] lg:py-[2vw] xl:py-[1vw]`}
          >
            Reset All Fields
          </Button>
        </section>
        {(imageLoading || imageResponse) && (
        <ImageView
          base64String={imageResponse}
          isLoading={imageLoading}
          isDark={isDark}
        />
        )}
      </main>
      <section ref={guideRef} className="max-w-full flex flex-col items-center gap-[4vw] mt-[10vw]">
        <div className="w-full flex flex-col items-center gap-[1vw]">
          <h2 className="lg:max-w-[45%] max-w-[70%] font-bold text-3xl md:text-5xl lg:text-3xl text-center">
            🎨 Complete Guide to Using the AI Image Generator for High-Quality,
            Creative & SEO-Optimized Visuals
          </h2>
          <p className="lg:max-w-[60%] max-w-[80%] text-2xl md:text-3xl lg:text-xl text-center">
            Our AI Image Generator is built for{" "}
            <span className="font-bold">
              creative design, visual storytelling, and digital content
              production
            </span>{" "}
            — without complex prompts. Simply describe your idea and customize
            the image settings to generate{" "}
            <span className="font-bold">
              stunning, high-resolution, and share-ready AI-generated images
            </span>{" "}
            in seconds.
          </p>
          <p className="lg:max-w-[60%] max-w-[80%] text-2xl md:text-3xl lg:text-xl text-center text-gray-300 mt-[1vw]">
            This guide explains{" "}
            <span className="font-bold">
              the idea, resolution, aspect ratio, and image format fields
            </span>
            , how to use them effectively, and how they improve visual quality,
            content performance, and search visibility.
          </p>
        </div>

        <div className="lg:max-w-[60%] max-w-[90%] space-y-16">
          <div className="max-w-full space-y-2 bg-gray-800/80 border border-gray-400/40 p-[4vw] lg:p-[1vw] rounded-xl">
            <h3 className="text-2xl md:text-3xl lg:text-2xl font-semibold text-white">
              💡 1. Image Idea
            </h3>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Purpose:</span> Defines
              the creative vision or concept for the image you want to generate.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Best Practice:</span>{" "}
              Describe the scene, subject, style, mood, and details clearly,
              such as “a futuristic city at sunset,” “minimalist product
              mockup,” or “realistic portrait photography.”
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Impact:</span> Produces
              visually accurate, detailed, and high-quality images aligned with
              your creative intent.
            </p>
          </div>

          <div className="w-full space-y-2 bg-gray-800/80 border border-gray-400/40 p-[1vw] rounded-xl">
            <h3 className="text-2xl md:text-3xl lg:text-2xl font-semibold text-white">
              📐 2. Resolution
            </h3>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Purpose:</span>{" "}
              Specifies the image quality and output size.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Best Practice:</span>{" "}
              Choose higher resolutions (such as 1080p or higher) for
              professional use, marketing materials, and high-quality
              publishing.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Impact:</span> Ensures
              crisp, sharp visuals suitable for websites, social media, ads, and
              digital marketing.
            </p>
          </div>

          <div className="w-full space-y-2 bg-gray-800/80 border border-gray-400/40 p-[1vw] rounded-xl">
            <h3 className="text-2xl md:text-3xl lg:text-2xl font-semibold text-white">
              📏 3. Aspect Ratio
            </h3>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Purpose:</span>{" "}
              Controls the shape and layout of the generated image.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Best Practice:</span>{" "}
              Select aspect ratios like 1:1 for social media, 16:9 for banners
              and presentations, or 9:16 for mobile and stories.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Impact:</span> Produces
              platform-optimized images for websites, ads, social media, and
              content marketing.
            </p>
          </div>

          <div className="w-full space-y-2 bg-gray-800/80 border border-gray-400/40 p-[1vw] rounded-xl">
            <h3 className="text-2xl md:text-3xl lg:text-2xl font-semibold text-white">
              🖼️ 4. Image Format
            </h3>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Purpose:</span> Defines
              the file type of the generated image.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Best Practice:</span>{" "}
              Choose JPG for web use, PNG for transparency and design work, or
              other formats based on your publishing needs.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Impact:</span> Ensures
              compatibility, faster loading, and optimal image quality for
              different platforms.
            </p>
          </div>
        </div>

        <div className="max-w-full lg:max-w-[45%] w-[80%] flex flex-col items-center pt-8 border-t border-gray-700 space-y-4">
          <h3 className="text-2xl md:text-3xl lg:text-2xl font-bold text-white">
            🚀 Why This Tool Improves Visual Content, Engagement & SEO
            Performance
          </h3>
          <p className="text-2xl lg:text-base">
            This AI Image Generator follows{" "}
            <span className="font-semibold text-white">
              proven visual design, content creation, and SEO best practices
            </span>{" "}
            to maximize results:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">
                High-Quality Visuals
              </span>{" "}
              – Generates sharp, professional-grade images
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">
                Creative Flexibility
              </span>{" "}
              – Supports multiple styles, formats, and layouts
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">SEO Optimization</span>{" "}
              – Improves content engagement, dwell time, and visual search
              performance
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Time Efficiency</span>{" "}
              – Creates images instantly without manual design work
            </li>
          </ul>

          <p className="text-2xl lg:text-base">
            It also aligns with{" "}
            <span className="font-semibold text-white">
              modern visual marketing, UX design, and SEO standards
            </span>
            , including:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">
              Visual content strategy and digital branding
            </li>
            <li className="text-2xl lg:text-base">
              Image optimization for websites and social platforms
            </li>
            <li className="text-2xl lg:text-base">
              Search engine image indexing and discoverability
            </li>
            <li className="text-2xl lg:text-base">
              Conversion-focused visual storytelling and design
            </li>
          </ul>
        </div>

        <div className="max-w-full lg:max-w-[45%] w-[80%] flex flex-col items-center pt-8 border-t border-gray-700 space-y-4">
          <h3 className="text-2xl md:text-3xl lg:text-2xl font-bold text-white">
            🧠 Final Tips for Best AI Image Generation Results
          </h3>
          <p className="text-2xl lg:text-base">
            For maximum visual quality, engagement, and search performance:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">
              Use{" "}
              <span className="font-semibold text-white">
                detailed and descriptive prompts
              </span>{" "}
              for better image accuracy
            </li>
            <li className="text-2xl lg:text-base">
              Select{" "}
              <span className="font-semibold text-white">
                appropriate resolution and aspect ratio
              </span>{" "}
              for your platform
            </li>
            <li className="text-2xl lg:text-base">
              Optimize images for{" "}
              <span className="font-semibold text-white">
                websites, social media, ads, blogs, and marketing campaigns
              </span>
            </li>
            <li className="text-2xl lg:text-base">
              Review output to ensure{" "}
              <span className="font-semibold text-white">
                style consistency, brand alignment, and visual clarity
              </span>
            </li>
            <li className="text-2xl lg:text-base">
              Use{" "}
              <span className="font-semibold text-white">
                SEO-friendly image practices and naming conventions
              </span>{" "}
              to boost discoverability
            </li>
          </ul>
        </div>
      </section>
      <section className="max-w-full lg:w-[60%] w-[90%] flex flex-col items-center mt-[10vw]">
        <FAQSection
          faqs={imageGeneratorFAQs}
          title="Frequently Asked Questions"
          subtitle="Everything you need to know about Magiwriter's AI CTA Generator and how it can transform your CTA game."
        />
      </section>
    </div>
  );
};

export default ImageGeneratorPage;
