import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useRef, useState } from "react";
import RestAllWritingOutputWindow from "@/components/outputScreen/restAllWriting";
import { AuroraText } from "@/components/ui/aurora-text";
import { ShinyButton } from "@/components/ui/shiny-button";
import FAQSection from "@/components/component/FAQSection";
import toast from "react-hot-toast";

const seoTagFaqs = [
  {
    question: "What is an AI SEO Tag Generator?",
    answer:
      "An AI SEO Tag Generator is a tool that automatically creates optimized meta tags, title tags, meta descriptions, and structured HTML tags based on your page title and target keywords. It helps improve search engine rankings, indexing, and click-through rates (CTR).",
  },
  {
    question: "How does the SEO Tag Generator improve Google rankings?",
    answer:
      "The tool uses SEO best practices to generate keyword-rich, search-engine-friendly metadata that helps search engines understand your content better, improving indexing, ranking potential, and organic traffic.",
  },
  {
    question: "What SEO tags does this tool generate?",
    answer:
      "It generates essential SEO tags such as meta title, meta description, meta keywords, Open Graph tags, Twitter Card tags, and structured HTML metadata for improved search visibility and social sharing.",
  },
  {
    question: "Is this SEO Tag Generator free to use?",
    answer:
      "Yes, the AI SEO Tag Generator is completely free to use, with no sign-up required, making it accessible for website owners, bloggers, marketers, and businesses looking to improve their SEO performance.",
  },
  {
    question: "Do I need SEO experience to use this tool?",
    answer:
      "No. This tool is designed for beginners and professionals alike. Simply enter your page title and keywords, and the AI generates fully optimized SEO tags without requiring any technical SEO knowledge.",
  },
  {
    question: "Can I use the generated SEO tags for any website or platform?",
    answer:
      "Yes. The generated SEO tags can be used for websites, blogs, landing pages, e-commerce stores, portfolios, and content management systems like WordPress, Shopify, and custom-built platforms.",
  },
  {
    question: "How accurate are the SEO tags generated by this tool?",
    answer:
      "The AI generates highly accurate, keyword-optimized, and search-engine-compliant SEO tags based on current SEO best practices, helping improve search rankings and content discoverability.",
  },
  {
    question: "Does this tool help improve click-through rate (CTR)?",
    answer:
      "Yes. The tool generates compelling, user-focused meta descriptions and optimized title tags designed to attract clicks, improve CTR, and increase organic traffic from search engine results pages (SERPs).",
  },
  {
    question: "Can I generate SEO tags for multiple pages?",
    answer:
      "Absolutely. You can generate SEO tags for unlimited pages by entering different titles and keywords, making it ideal for blogs, websites, product pages, and marketing campaigns.",
  },
  {
    question: "Is this tool suitable for local SEO and niche websites?",
    answer:
      "Yes. By entering location-based or niche-specific keywords, the tool can generate SEO tags optimized for local SEO, industry-specific content, and targeted search visibility.",
  },
  {
    question: "How does this SEO Tag Generator compare to manual SEO optimization?",
    answer:
      "Unlike manual SEO optimization, which is time-consuming and requires expertise, this AI tool instantly generates optimized SEO tags based on proven on-page SEO strategies, saving time while maintaining high quality.",
  },
  {
    question: "Will these SEO tags work for social media previews?",
    answer:
      "Yes. The tool generates Open Graph and Twitter Card tags, ensuring your content displays correctly on platforms like Facebook, X (Twitter), LinkedIn, and other social networks, improving social engagement and visibility.",
  },
];


const SeotagGeneratorPage = () => {
  const guideRef = useRef(null);
  const [isDark, setIsDark] = useState(true);
  const [title, setTitle] = useState("");
  const [keywords, setKeywords] = useState("");

  const [seotagLoading, setSeotagLoading] = useState(false);
  const [seotagResponse, setSeotagResponse] = useState("");
  const handleSeotagGenerate = async () => {
    if(!title || title.trim() === "" || !keywords || keywords.trim() === "") {
      toast.error("Please fill in both the title and keywords fields!");
      return;
    }
    try {
      setSeotagLoading(true);
      const res = await fetch("https://www.magiwriter.com/api/generate/seotag", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
        body: JSON.stringify({ title, keywords }),
      });
      const response = await res.json();
      setSeotagResponse(response.seotag);
    } catch (error) {
      console.error("Error generating Seotag!:", error);
    } finally {
      setSeotagLoading(false);
    }
  };

  const handleResetFields = () => {
    setTitle("");
    setKeywords("");
  };

  return (
    <div className="max-w-screen flex flex-col items-center gap-[3vw] mt-[1vw] text-white">
      <header className="w-full flex flex-col items-center gap-[1vw] mt-[14vw] md:mt-[14vw] lg:mt-[8vw]">
        <h1 className="font-bold text-4xl md:text-5xl lg:text-4xl font-nunito">
          <AuroraText
            colors={[
              "#60efff",
              "#0061ff",
              "#40c9ff",
              "#cbff49",
              "#ff8989",
              "#fff95b",
            ]}
            speed={1.5}
          >
            AI Meta Tag Generator
          </AuroraText>
        </h1>
        <h2 className="max-w-[60%] text-center font-semibold text-2xl md:text-4xl lg:text-2xl font-nunito text-gray-300">
          Create fully optimized, human-quality blog blogs in seconds using
          structured inputs for keywords, tone, audience, SEO, images, tables,
          FAQs, and more—no prompt writing required.
        </h2>
      </header>
      <section className="w-full flex flex-col items-center gap-[1vw]">
        <p className="max-w-[40%] text-center text-xl md:text-3xl lg:text-2xl font-nunito text-gray-100">
          Want to know how you could leverage Magiwriter's AI Blog Writer to
          generate top class industry grade blogs with best SEO techniques? Look
          no further, just check down bellow.
        </p>
        <ShinyButton onClick={()=> guideRef.current.scrollIntoView({behavior: "smooth"})} className={"bg-white/15 md:text-4xl lg:text-sm m-0"}>
          Check Full Guide
        </ShinyButton>
      </section>
      <main
        className={`w-[95%] xl:w-[60%] flex flex-col items-center gap-[6vw] lg:gap-[5vw] xl:gap-[2vw] border ${
          isDark
            ? "bg-black/35 border-gray-300/25"
            : "bg-white/55 border-gray-400/15"
        } blur-in-3xl z-10 p-[4vw] xl:p-[2vw] xl:my-[1vw] rounded-3xl font-nunito`}
      >
        <section className="w-full flex flex-col items-center gap-[5vw] xl:gap-[1vw]">
          <div className="w-full flex flex-col items-start gap-[2vw] xl:gap-[0.5vw]">
            <Label htmlFor="message">
              Put the page title here to generate Seotag
            </Label>
            <Textarea
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className={`border h-[14vw] xl:h-[5vw] ${
                isDark
                  ? "bg-gray-900 text-white placeholder:text-gray-300 border-gray-600"
                  : "bg-white text-black placeholder:text-gray-400"
              } shadow-lg resize-none overflow-auto text-xl md:text-3xl lg:text-base p-[2vw] lg:p-[1vw] xl:p-[0.5vw]`}
              placeholder="Title here..."
            />
          </div>
          <div className="w-full flex flex-col items-start gap-[2vw] xl:gap-[0.5vw]">
            <Label              className={"text-xl md:text-3xl lg:text-base"} htmlFor="message">Put keywords here</Label>
            <Textarea
              value={keywords}
              onChange={(e) => setKeywords(e.target.value)}
              className={`border h-[14vw] xl:h-[5vw] ${
                isDark
                  ? "bg-gray-900 text-white placeholder:text-gray-300 border-gray-600"
                  : "bg-white text-black placeholder:text-gray-400"
              } shadow-lg resize-none overflow-auto text-xl md:text-3xl lg:text-base p-[2vw] lg:p-[1vw] xl:p-[0.5vw]`}
              placeholder="Keywords here..."
            />
          </div>
        </section>
        <section className="w-full flex flex-col items-center gap-[5vw] xl:gap-[1vw]">
          <Button
            onClick={handleSeotagGenerate}
            className={`w-full font-nunito cursor-pointer bg-linear-from-l bg-linear-to-r from-blue-500/50 via-pink-500/70 to-orange-500/65 ${
              isDark
                ? "text-white hover:bg-white/20"
                : "text-black hover:bg-black/20"
            } shadow-xl text-xl md:text-3xl lg:text-base px-[2vw] lg:px-[1vw] xl:px-[0.5vw] py-[4vw] lg:py-[2vw] xl:py-[1vw] transition-all duration-200`}
          >
            Generate SEO Tag
          </Button>
          <Button
            onClick={handleResetFields}
            variant={"seotag"}
            className={`w-full font-nunito cursor-pointer ${
              isDark
                ? "hover:bg-red-700/20 hover:text-white bg-gray-800/55 border-gray-600/80 text-white"
                : "hover:bg-red-700/20 hover:text-black bg-white text-black"
            } transition-all duration-200 text-xl md:text-3xl lg:text-base px-[2vw] lg:px-[1vw] xl:px-[0.5vw] py-[4vw] lg:py-[2vw] xl:py-[1vw]`}
          >
            Reset All Fields
          </Button>
        </section>
        {(seotagLoading || seotagResponse) && (
          <RestAllWritingOutputWindow
            restAllWritingMarkdown={seotagResponse}
            isLoading={seotagLoading}
            isDark={isDark}
          />
        )}
      </main>
      <section ref={guideRef} className="max-w-full flex flex-col items-center gap-[4vw] mt-[10vw]">
        <div className="w-full flex flex-col items-center gap-[1vw]">
          <h2 className="lg:max-w-[45%] max-w-[70%] font-bold text-3xl md:text-5xl lg:text-3xl text-center">
            💡 Complete Guide to Using the AI SEO Tag Generator for Higher
            Rankings & Search Visibility
          </h2>
          <p className="lg:max-w-[60%] max-w-[80%] text-2xl md:text-3xl lg:text-xl text-center">
            Our AI SEO Tag Generator is built for{" "}
            <span className="font-bold">
              search engine optimization, content visibility, and higher
              click-through rates
            </span>{" "}
            — without complex SEO tools. Simply enter your page title and
            keywords to generate{" "}
            <span className="font-bold">
              accurate, high-performing, and SEO-optimized meta tags
            </span>{" "}
            in seconds.
          </p>
          <p className="lg:max-w-[60%] max-w-[80%] text-2xl md:text-3xl lg:text-xl text-center text-gray-300 mt-[1vw]">
            This guide explains{" "}
            <span className="font-bold">the title and keywords fields</span>,
            how to use them effectively, and how they improve indexing,
            rankings, traffic, and overall SEO performance.
          </p>
        </div>

        <div className="lg:max-w-[60%] max-w-[90%] space-y-16">
          <div className="max-w-full space-y-2 bg-gray-800/80 border border-gray-400/40 p-[4vw] lg:p-[1vw] rounded-xl">
             <h3 className="text-2xl md:text-3xl lg:text-2xl font-semibold text-white">
              🏷️ 1. Page Title
            </h3>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Purpose:</span> Defines
              the main title of the webpage for which SEO tags will be
              generated.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Best Practice:</span>{" "}
              Enter your page title exactly as it appears in search results,
              such as “Best AI Writing Tools,” “Free Resume Builder Online,” or
              “Top Marketing Software.”
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Impact:</span> Ensures
              optimized title tags, accurate meta descriptions, and improved
              click- through rates (CTR) in search engine results pages (SERPs).
            </p>
          </div>

          <div className="w-full space-y-2 bg-gray-800/80 border border-gray-400/40 p-[1vw] rounded-xl">
            <h3 className="text-2xl md:text-3xl lg:text-2xl font-semibold text-white">🔑 2. Keywords</h3>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Purpose:</span>{" "}
              Specifies the target keywords and phrases related to your page
              content.
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Best Practice:</span>{" "}
              Enter primary and secondary keywords such as “SEO tools,” “meta
              tag generator,” “on-page SEO,” “content optimization,” or “Google
              ranking.”
            </p>
            <p className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Impact:</span> Produces
              keyword-rich meta tags, Open Graph tags, and structured HTML tags
              that improve indexing, discoverability, and organic traffic.
            </p>
          </div>
        </div>

        <div className="max-w-full lg:max-w-[45%] w-[80%] flex flex-col items-center pt-8 border-t border-gray-700 space-y-4">
          <h3 className="text-2xl md:text-3xl lg:text-2xl font-bold text-white">
            📈 Why This Tool Improves SEO, Rankings & Search Performance
          </h3>
          <p className="text-2xl lg:text-base">
            This AI SEO Tag Generator follows{" "}
            <span className="font-semibold text-white">
              proven SEO, content optimization, and search marketing best
              practices
            </span>{" "}
            to maximize results:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Search Rankings</span>{" "}
              – Creates optimized meta tags that improve Google and Bing
              visibility
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">
                Click-Through Rate (CTR)
              </span>{" "}
              – Generates compelling meta descriptions that attract more clicks
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Content Indexing</span>{" "}
              – Helps search engines understand and rank your content faster
            </li>
            <li className="text-2xl lg:text-base">
              <span className="font-semibold text-white">Organic Traffic</span>{" "}
              – Drives more qualified visitors through improved SEO performance
            </li>
          </ul>

          <p className="text-2xl lg:text-base">
            It also aligns with{" "}
            <span className="font-semibold text-white">
              modern SEO standards and on-page optimization frameworks
            </span>
            , including:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">On-page SEO and metadata optimization</li>
            <li className="text-2xl lg:text-base">Search engine indexing and crawling best practices</li>
            <li className="text-2xl lg:text-base">Content marketing and keyword targeting strategies</li>
            <li className="text-2xl lg:text-base">Conversion-focused SEO and SERP optimization</li>
          </ul>
        </div>

        <div className="max-w-full lg:max-w-[45%] w-[80%] flex flex-col items-center pt-8 border-t border-gray-700 space-y-4">
          <h3 className="text-2xl md:text-3xl lg:text-2xl font-bold text-white">
            🧠 Final Tips for Best SEO Tag Generation Results
          </h3>
          <p className="text-2xl lg:text-base">For maximum search visibility, rankings, and traffic growth:</p>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li className="text-2xl lg:text-base">
              Use{" "}
              <span className="font-semibold text-white">
                clear, descriptive page titles
              </span>{" "}
              that match user search intent
            </li>
            <li className="text-2xl lg:text-base">
              Choose{" "}
              <span className="font-semibold text-white">
                relevant and high-volume keywords
              </span>{" "}
              to improve ranking potential
            </li>
            <li className="text-2xl lg:text-base">
              Optimize tags for{" "}
              <span className="font-semibold text-white">
                websites, blogs, landing pages, and e-commerce stores
              </span>
            </li>
            <li className="text-2xl lg:text-base">
              Test multiple tag variations to find the{" "}
              <span className="font-semibold text-white">
                highest-performing metadata
              </span>
            </li>
            <li className="text-2xl lg:text-base">
              Use{" "}
              <span className="font-semibold text-white">
                SEO-friendly language, emotional triggers, and call-to-action
                phrases
              </span>{" "}
              to boost click-through rates
            </li>
          </ul>
        </div>
      </section>
      <section className="max-w-full lg:w-[60%] w-[90%] flex flex-col items-center mt-[10vw]">
        <FAQSection
          faqs={seoTagFaqs}
          title="Frequently Asked Questions"
          subtitle="Everything you need to know about Magiwriter's AI SEO Tag Generator and how it can transform your SEO game."
        />
      </section>
    </div>
  );
};

export default SeotagGeneratorPage;
