const TermsOfUsePage = () => {
  return (
    <div className="max-w-screen flex flex-col items-center gap-[3vw] mt-[2vw] text-white">
      <div className="max-w-3xl mx-auto p-8 rounded-2xl shadow-sm">
        
        <h1 className="text-3xl font-bold mb-4 ">
          Terms of Use
        </h1>
        <p className="text-sm mb-8">
          <strong>Effective Date:</strong> 25.02.2026
        </p>

        <section className="space-y-6">

          <div>
            <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Magiwriter, you agree to be bound by these
              Terms of Use. If you do not agree, you must not use the platform.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">2. Description of Service</h2>
            <p>
              Magiwriter is an AI-powered writing platform that generates text
              content based on user inputs. The service is provided on an "as is"
              and "as available" basis and may evolve over time.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">3. User Accounts</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must provide accurate and complete information.</li>
              <li>You are responsible for maintaining account security.</li>
              <li>You are responsible for all activity under your account.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">4. Acceptable Use</h2>
            <p>You agree not to use the platform to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Generate illegal, harmful, or abusive content</li>
              <li>Violate intellectual property rights</li>
              <li>Attempt to exploit, reverse engineer, or disrupt the service</li>
              <li>Upload or distribute malware or harmful code</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">5. AI-Generated Content</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                Outputs are generated by AI and may be inaccurate or incomplete.
              </li>
              <li>
                You are responsible for reviewing and validating generated content.
              </li>
              <li>
                We do not guarantee originality or uniqueness of outputs.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">6. Ownership and Rights</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You retain ownership of your inputs.</li>
              <li>
                You may use generated outputs for personal or commercial purposes.
              </li>
              <li>
                We may use anonymized data to improve the service.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">7. Third-Party Services</h2>
            <p>
              Our platform may rely on third-party providers (such as AI APIs,
              hosting, and analytics). We are not responsible for their services
              or policies.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">8. Service Availability</h2>
            <p>
              We do not guarantee uninterrupted or error-free service. Features
              may change, be limited, or discontinued at any time.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate access to the service
              at our discretion, including for violations of these terms.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">10. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Magiwriter shall not be
              liable for any indirect, incidental, or consequential damages
              resulting from your use of the service.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">11. Disclaimer</h2>
            <p>
              The service is provided without warranties of any kind. We disclaim
              all warranties, express or implied, including fitness for a
              particular purpose and non-infringement.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">12. Changes to Terms</h2>
            <p>
              We may update these Terms of Use from time to time. Continued use
              of the service constitutes acceptance of the updated terms.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">13. Governing Law</h2>
            <p>
              These terms shall be governed by and interpreted in accordance with
              applicable laws of your jurisdiction.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-2">14. Contact</h2>
            <p>
              For any questions regarding these terms, contact:{" "}
              <span className="text-blue-600">magiwriterai@gmail.com</span>
            </p>
          </div>

        </section>
      </div>
    </div>
  );
};

export default TermsOfUsePage;
